dist: bionic
language: python
cache:
  pip: true
python:
  - "3.6"
  - "3.7"
  - "3.8-dev"
  - "nightly"

install:
  - pip install -r test-requirements.txt --progress-bar=off
  - flit install -s

script:
  - black --check -S -l 100 -t py36 spellrst.py tests
  - make test
  # dogfood
  - spellrst README.rst

after_success:
  - codecov
